
// THIS FILE WAS AUTO-GENERATED BY IMPACT.
// DO NOT MODIFY THIS FILE!
// Write to package.impact.js instead.

Package.describe({
  summary:  'Impact (alpha)',
  name:     'impact:module-forum',
  version:  '0.1.0',
});

Package.onUse(function (api, where) {
  
  
  api.use(['impact:impact'], ['client', 'server']);
  api.imply(['impact:impact'], ['client', 'server']);


  //-- IMPACT: FILES --//

  api.addFiles([
    "both/_index.js",
    "both/init.js",
    "both/initDb.js",
    "both/initRoutes.js",
  ], ["client", "server"]);


  api.addFiles([
    "client/content/edit/edit.html",
    "client/content/index/index.html",
    "client/views/topic/topic.html",
    "client/content/edit/_editController.js",
    "client/content/edit/edit.js",
    "client/content/index/_indexController.js",
    "client/content/index/index.js",
    "client/content/new/_newController.js",
    "client/views/topic/_topicController.js",
    "client/views/topic/topic.js",
  ], "client");


  api.addFiles([
    "server/initFake.js",
    "server/initPrivileges.js",
    "server/initPublications.js",
  ], "server");


});
