
// THIS FILE WAS AUTO-GENERATED BY IMPACT.
// DO NOT MODIFY THIS FILE!
// Write to package.impact.js instead.

Package.describe({
  summary:  'Impact (alpha) Semantic UI package',
  name:     'impact:semantic',
  version:  '0.1.0',
});

Package.on_use(function (api, where) {
  
  api.use(['impact:impact'], ['client', 'server']);
  api.imply(['impact:impact'], ['client', 'server']);

  
  //-- IMPACT: FILES --//

  api.addFiles([
    "client/semantic.css",
    "client/semantic.js",
  ], "client");


  api.addFiles([
    "files/fonts/basic.icons.eot",
    "files/fonts/basic.icons.svg",
    "files/fonts/basic.icons.ttf",
    "files/fonts/basic.icons.woff",
    "files/fonts/icons.eot",
    "files/fonts/icons.otf",
    "files/fonts/icons.svg",
    "files/fonts/icons.ttf",
    "files/fonts/icons.woff",
    "files/images/loader-large-inverted.gif",
    "files/images/loader-large.gif",
    "files/images/loader-medium-inverted.gif",
    "files/images/loader-medium.gif",
    "files/images/loader-mini-inverted.gif",
    "files/images/loader-mini.gif",
    "files/images/loader-small-inverted.gif",
    "files/images/loader-small.gif",
  ], "client");


});
