
// THIS FILE WAS AUTO-GENERATED BY IMPACT.
// DO NOT MODIFY THIS FILE!
// Write to package.impact.js instead.

Package.describe({
  summary:  'Semantic templates for Autoform',
  name:     'anti:semantic-autoform',
  version:  '0.0.0',
});

Package.onUse(function (api, where) {
  
  //-- IMPACT: FILES --//

});
